# Generated by Django 4.0.2 on 2022-09-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=11, verbose_name='номер телефона')),
                ('fio', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='город')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='изображение')),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='должность')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='баланс')),
            ],
        ),
    ]
